### ISSUE TITLE
Playing Sounds for Individual Players?

### ISSUE THREAD

**Issue by xs4u** [IITPP-Roblox/LocalAudio#1]
how do I play a sound from client, or play it from server but only for one player?

**Comment by TheNexusAvenger** [comment]
That use case isn't supported. Sounds are sent to everyone with no way to filter who. Without changing the code, there is no way to do this *on the server*. Doing it on the client is supported though.

**Comment by xs4u** [comment]
oh, my script broke I guess

**Comment by xs4u** [comment]
found a weird issue, the script got paused after I ran client playaudio

after server ran it, the script resumed

**Comment by TheNexusAvenger** [comment]
Going to close this in favor of using #2.
