### ISSUE TITLE
Audios called from client run only after server calls the same audio

### ISSUE THREAD

**Issue by xs4u** [IITPP-Roblox/LocalAudio#2]
and the script literally waits until the server calls that audio

**Comment by TheNexusAvenger** [comment]
IITPP calls audios on the client without any issues. We need more information.

**Comment by xs4u** [comment]
so, I don’t really know what else can I explain but:

for example, if I use ;localscript (Adonis, and play audio like that) nothing happens, the same happens with normal local scripts, but if the server does PlayAudio with that ID (no matter how long ago did client call the playaudio) all play at the same time (LocalScript ones, and the server one)

localscript I made is located in startergui btw

**Comment by TheNexusAvenger** [comment]
A code example of what you have *with no external systems like Adonis* would give clarity to what is going on.

**Comment by xs4u** [comment]
so, I decided to make subtitles for EAS (Zombies event)

```lua
LocalAudio:PlayAudio("EAS.EASZombiesEvent")
```
I'll give a better example soon

**Comment by xs4u** [comment]
https://user-images.githubusercontent.com/92084563/218022489-b1369736-6051-443e-9d05-68e3f9aa75fc.mp4

moving the require of LocalAudio made 2 start at the same time

**Comment by TheNexusAvenger** [comment]
It looks like you aren't doing the server setup. From the README:
> LocalAudio is not self-contained and requires additional setup to use. On the server, the module only needs to be `require`d.

Try adding `require` somewhere in a script on a server and see what happens.

**Comment by xs4u** [comment]
ok, will try that soon

**Comment by xs4u** [comment]
worked, thanks!
